[package]
name = "axum-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "axum-app"
path = "src/main.rs"

[lib]
name = "axum_app"
path = "src/lib.rs"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.218", features = ["derive"] }
